# Generated by Django 4.1.2 on 2022-11-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio_object',
            name='title',
            field=models.CharField(default='untitled', max_length=500),
            preserve_default=False,
        ),
    ]
