# Generated by Django 4.1.2 on 2022-12-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_app', '0002_audio_object_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio_object',
            name='category',
            field=models.CharField(default='Nature', max_length=500, ),
        ),
    ]
