# Generated by Django 4.1.2 on 2022-12-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_app', '0003_audio_object_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio_object',
            name='category',
            field=models.CharField(choices=[('N', 'Nature'), ('M', 'Meditation'), ('GM', 'Guided Meditation'), ('BE', 'Breathing Exercise'), ('S', 'Stories')], default='N', max_length=500),
        ),
    ]
