# Generated by Django 4.1.2 on 2022-12-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_app', '0004_alter_audio_object_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio_object',
            name='category',
            field=models.CharField(choices=[('NS', 'Nature Sounds'), ('GM', 'Guided Meditation'), ('BE', 'Breathing Exercises'), ('S', 'Stories'), ('BB', 'Binural Beats'), ('IR', 'Indian Ragas'), ('MM', 'Meditation Music'), ('SGM', 'Short Guided Mediations'), ('VC', 'Vocal Chanting')], default='MM', max_length=500),
        ),
    ]
