# Generated by Django 4.1.2 on 2022-12-23 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audio_app', '0006_alter_audio_object_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio_app.audio_object')),
                ('sourcePlaylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio_app.playlist')),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='audios',
            field=models.ManyToManyField(blank=True, related_name='audio_files', through='audio_app.PlaylistMapping', to='audio_app.audio_object'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
