# Generated by Django 4.1.2 on 2022-12-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_app', '0007_playlist_playlistmapping_playlist_audios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio_object',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
