# Generated by Django 4.1.2 on 2023-01-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_app', '0009_alter_audio_object_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio_object',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
